---
title: "Parameter guide"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Parameter guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The below table details the variable names expected in the input data set (*Variable*), the expected data type or a list of valid entried for each variable (*Valid data entry*), and whether the variable is required.

Note that entries in the *Valid data entry* column provided as a list of string entries must be included in the data file exactly as presented below (including case sensitivity).

|**Variable**           |**Description**                                                                                                                                                                                             |**Valid data entry**                                                                                                                                                                                          |**Required field**                                                                                                                                                        |**Default**                                 |
|:----------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------|
|`"name"`                   |Product name for identity purposes.                                                                                                                                                                          |String format                                                                                                                                                                                                 |Optional                                                                                                                                                             |                                            |
|`"brand"`                  |Product brand for identity purposes.                                                                                                                                                                         |String format                                                                                                                                                                                                 |Optional                                                                                                                                                             |                                            |
|`"product_category"`       |Enter one of the HFSS product placement legislation categories.                                                                                                                                              |One of:</br>`"Soft drink"`, `"Savoury snack"`, `"Breakfast cereals"`, `"Confectionary"`, `"Ices"`, `"Cakes"`, `"Sweet biscuits and bars"`, `"Morning goods"`, `"Desserts and puddings"`, `"Yoghurts"`, `"Pizza"`, `"Potato products"`, `"Ready meals and meal centres"`, `"Other"`|Optional                                                                                         |                                            |
|`"product_type"`           |Used to determine NPM score threshold (1 for drinks, 4 for foods).                                                                                                                                           |One of:</br>`"Food"`, `"Drink"`                                                                                                                                                                                                    |Required                                                                                                                                        |Default is `"Food"`, unless `"Product category" == "Soft Drink"`|
|`"food_type"`              |Used to assign specific gravity conversion calculation for food products sold by volume (rather than weight).                                                                                                |One of:</br>`"Ice cream"`, `"Ice lolly"`, `"Mayonnaise"`, `"Maple syrup"`, `"Single cream"`, `"Double cream"`, `"Whipping cream"`                                                                                                                     |Optional If food type is not entered a 1:1 mlg specific gravity ratio will be assumed                                        |1:1 specific gravity ratio will be assumed. |
|`"drink_format"`           |Used to determine if dilution calculation is required and for specific gravity conversion.                                                                                                                   |One of:</br>`"Ready"`, `"Cordial"`, `"Powdered"`                                                                                                                                                                                      |Optional If drink_format is not entered drink will be assumed ready to drink and no dilution calculation will be carried out                 | Default is `"Ready to drink"` |
|`"drink_type"`             |Used to assign specific gravity conversion calculation for drinks.                                                                                                                                           |One of:</br>`"Semi-skimmed milk"`, `"Carbonated/juice drink"`, `"Diet carbonated drink"`, `"Energy drink"`, `"Cordial/squash ready to drink"`, `"Cordial/squash undiluted"`                                                                       |Optional If drink type is not entered a 1:1 ml:g specific gravity ratio will be assumed                                          |1:1 specific gravity ratio will be assumed. |
|`"weight_g"`               |Mass of product if solid.</br>Used to determine if a specific gravity calculation is required.</br>This should be the mass for which nutrition information is presented e.g. per 100g or per portion (enter portion size).|Numeric                                                                                                                                                                                                       |Optional Only enter weight for solid foods with weight expressed in grams For powdered drinks enter weight of powder in grams for dilution and specific gravity conversion|                                            |
|`"volume_ml"`              |Volume of product if liquid.</br>Enter volume for drinks and for food products expressed in volume terms (e.g. ice cream).</br>Used for specific gravity conversion.                                                   |Numeric                                                                                                                                                                                                       |Optional Only enter for drinks and foods expressed in volume terms (ml)                                                                                   |                                            |
|`"volume_water_ml"`        |Volume of water added for diluted products.                                                                                                                                                                  |Numeric                                                                                                                                                                                                       |Required for drink products of format cordial or powdered where nutrition information is not given for the product as consumed                                      |                                            |
|`"nutrition_info"`         |Enter for drinks only.</br>How nutrition info is presented (e.g. with dilution instructions). Used for specific gravity conversion.                                                                                                                  |One of:</br>`"As consumed"`, `"Preparation instructions given"`, `"Preparation instructions not given"`                                                                                                                               |Required for drink products of format cordial or powdered. </br>Not required for other product types.     | If `"drink_format" == NULL`, default is `Diet carbonated drink` (with specific gravity of 1.00).</br>If `"drink_format" == "Powdered drink"` or `"Cordial/squash"`, the default is `"As consumed (diluted)"` |
|`"energy_measurement_kj"`  |Energy content of the product (kj) expressed per given weight/volume (e.g. /100g or per portion).                                                                                                            |Numeric                                                                                                                                                                                                       |Required if energy_measurement_kcal given                                                                                                                                 |                                            |
|`"energy_measurement_kcal"`|Energy content of the product (kcal) expressed per given weight/volume (e.g. /100g or per portion).                                                                                                          |Numeric                                                                                                                                                                                                       |Required if energy_measurement_kj not given                                                                                                                               |                                            |
|`"sugar_measurement_g"`    |Sugar content of the product (g) expressed per given weight/volume (e.g./100g or per portion).                                                                                                                |Numeric                                                                                                                                                                                                       |Required                                                                                                                                                                  |                                            |
|`"satfat_measurement_g"` |Saturated fat content of the product (g) expressed per given weight/volume (e.g./100g or per portion).                                                                                                       |Numeric                                                                                                                                                                                                       |Required                                                                                                                                                                  |                                            |
|`"salt_measurement_g"`     |Salt content of the product (g) expressed per given weight/volume (e.g./100g or per portion).                                                                                                                |Numeric                                                                                                                                                                                                       |Required if sodium_measurement_mg not given                                                                                                                               |                                            |
|`"sodium_measurement_mg"`  |Sodium content of the product (mg) expressed per given weight/volume (e.g. /100g or per portion).                                                                                                            |Numeric                                                                                                                                                                                                       |Required if alt_measurement_g not given                                                                                                                                   |                                            |
|`"fibre_measurement_nsp"`  |Fibre content of the product (g) measured by the NSP method expressed per given weight/volume (e.g. /100g or per portion). If unsure whether fibre is NSP or AOAC assume AOAC and leave NSP blank.           |Numeric                                                                                                                                                                                                       |Required if fibre_measurement_aoac not given                                                                                                                              |                                            |
|`"fibre_measurement_aoac"` |Fibre content of the product(g) measured by the AOAC method expressed per given weight/volume (e.g./100g or per portion). If unsure whether fibre is NSP or AOAC assume AOAC and leave NSP blank.            |Numeric                                                                                                                                                                                                       |Required if fibre. measurement_nsp not given                                                                                                                              |                                            |
|`"protein_measurement_g"`  |Protein content of the product (g) expressed per given weight/volume (e.g. /100g or per portion).                                                                                                            |Numeric                                                                                                                                                                                                       |Required                                                                                                                                                                  |                                            |
|`"fvn_measurement_percent"`|The percent of fruit, vegetables and nuts in the product (by weight)                                                                                                                                         |Numeric                                                                                                                                                                                                       |Required If the percentage of fruit vegetables and nuts is unknown enter '0' (zero)                                                                                       |0 (zero)                                    |
