#' Required parameter checking function
#'
#' This function processes the data.frame object with product data
#' and check for required parameters. It returns a report table which
#' contains row indices of missing required parameters. Please
#' see guidance on required and default parameters for more information
#' and before processing your data.
#'
#' @param data_frame a data.frame object
#' @return report_data a data.frame object with information on missing parameters
#' @seealso [SaveReport()],[AutoDefaultParamCheck()],[AutoDefaultParamNote()],[ManualParamUpdate()]
#' @importFrom stats setNames
#' @export
ReqParamCheck <- function(data_frame) {
    expected_column_names <- c("name", "brand", "product_category",
    "product_type", "food_type", "drink_format","drink_type",
    "nutrition_info", "energy_measurement_kj", "energy_measurement_kcal",
    "sugar_measurement_g", "satfat_measurement_g", "salt_measurement_g",
    "sodium_measurement_mg", "fibre_measurement_nsp", "fibre_measurement_aoac",
    "protein_measurement_g", "fvn_measurement_percent", "weight_g",
    "volume_ml", "volume_water_ml")
    auto_defaults <- c("drink_format","food_type","drink_type")
    optional_names <- c("name", "brand", "product_category")
    report_data <- setNames(data.frame(matrix(ncol = length(expected_column_names),nrow = 1)), expected_column_names)
    print("Please note that the following parameters are optional and are not checked here:")
    print(paste(optional_names))
    print("Please note that the following parameters have automatically applied defaults if missing and are not checked by this function:")
    print(paste(auto_defaults))
    print("If you wish to check the presence of these parameters and record when defaults are used,")
    print("please see the `AutoDefaultParamCheck()` and `AutoDefaultParamNote()` functions")
    print("Please see the `SaveReport()` function to output a csv version of this report table.")
    # the basic required parameters
    report_data$product_type[1] <- list(
        which((data_frame$product_type == "") | is.na(data_frame$product_type))
        )
    report_data$sugar_measurement_g[1] <- list(
        which((data_frame$sugar_measurement_g == "") | is.na(data_frame$sugar_measurement_g))
        )
    report_data$satfat_measurement_g[1] <- list(
        which((data_frame$satfat_measurement_g == "") | is.na(data_frame$satfat_measurement_g))
        )
    report_data$protein_measurement_g[1] <- list(
        which((data_frame$protein_measurement_g == "") | is.na(data_frame$protein_measurement_g))
        )
    report_data$fvn_measurement_percent[1] <- list(
        which((data_frame$fvn_measurement_percent == "") | is.na(data_frame$fvn_measurement_percent))
        )
    # categories where one option or another is required
    # "energy_measurement_kj", "energy_measurement_kcal",
    report_data$energy_measurement_kj[1] <- list(
        which(((data_frame$energy_measurement_kj == "") | is.na(data_frame$energy_measurement_kj)) & 
        ((data_frame$energy_measurement_kcal == "") | is.na(data_frame$energy_measurement_kcal)))
    )
    # "salt_measurement_g", "sodium_measurement_mg",
    report_data$salt_measurement_g[1] <- list(
        which(((data_frame$salt_measurement_g == "") | is.na(data_frame$salt_measurement_g)) & 
        ((data_frame$sodium_measurement_mg == "") | is.na(data_frame$sodium_measurement_mg)))
    )
    #"fibre_measurement_nsp", "fibre_measurement_aoac",#
    report_data$fibre_measurement_nsp[1] <- list(
        which(((data_frame$fibre_measurement_nsp == "") | is.na(data_frame$fibre_measurement_nsp)) & 
        ((data_frame$fibre_measurement_aoac == "") | is.na(data_frame$fibre_measurement_aoac)))
    )
    #"weight_g", "volume_ml",
    report_data$weight_g[1] <- list(
        which(((data_frame$weight_g == "") | is.na(data_frame$weight_g)) & 
        ((data_frame$volume_ml == "") | is.na(data_frame$volume_ml)))
    )
    # parameters dependent on categories
    # "nutrition_info"
    report_data$nutrition_info[1] <- list(
        which(((data_frame$nutrition_info == "") | is.na(data_frame$nutrition_info)) & 
        ((data_frame$drink_format == "Cordial") | (data_frame$drink_format == "Powdered")))
    )
    # "volume_water_ml"
    report_data$volume_water_ml[1] <- list(
        which(((data_frame$volume_water_ml == "") | is.na(data_frame$volume_water_ml)) & 
        ((data_frame$drink_format == "Cordial") | (data_frame$drink_format == "Powdered")) &
        ((data_frame$nutrition_info == "preparation instructions given")))
    )
    return(report_data)
}

#' Save report function
#'
#' This function saves a transposed version of the report generated by `ReqParamCheck()`
#'
#' @param data_frame a data.frame object
#' @param file_path a chr object containing relative filepath from the current working directory, to save csv
#' @return saves csv file
#' @seealso [ReqParamCheck()],[AutoDefaultParamCheck()],[AutoDefaultParamNote()],[ManualParamUpdate()]
#' @importFrom utils write.csv
#' @export
SaveReport <- function(data_frame, file_path) {
    write.csv(t(data_frame), file_path)
}

#' Required parameter with automatic defaults checking function
#'
#' This function checks whether values for `drink_format`, `drink_type`, or
#' `food_type` are provided. These have default settings which are automatically
#' applied if a value is not supplied. Please read the documentation for further detail.
#' To record use of default parameters, please see `AutoDefaultParamNote()`.
#'
#' @param data_frame a data.frame object with product data
#' @param report_data a data.frame object produced by `ReqParamCheck()` with information on missing parameters
#' @return report_data a data.frame object updated with information on missing parameters
#' @seealso [ReqParamCheck()],[AutoDefaultParamNote()],[ManualParamUpdate()]
#' @export
AutoDefaultParamCheck <- function(data_frame, report_data) {
    report_data$drink_format[1] <- list(
        which(((data_frame$drink_format == "") | is.na(data_frame$drink_format)) & 
        ((data_frame$product_type == "Drink")))
    )
    report_data$drink_type[1] <- list(
        which(((data_frame$drink_type == "") | is.na(data_frame$drink_type)) & 
        ((data_frame$product_type == "Drink")))
    )
    report_data$food_type[1] <- list(
        which(((data_frame$food_type == "") | is.na(data_frame$food_type)) & 
        ((data_frame$product_type == "Food")))
    )
    return(report_data)
}

#' Required parameter with automatic defaults recording function
#'
#' This function checks whether values for `drink_format`, `drink_type`, or
#' `food_type` are provided and records in the product data frame if defaults
#' will be used for analysis.
#'
#' @param data_frame a data.frame object with product data
#' @param report_data a data.frame object produced by `ReqParamCheck()` with information on missing parameters
#' @return data_frame the product data with an additional column recording default use
#' @seealso [AutoDefaultParamCheck()],[ReqParamCheck()]
#' @export
AutoDefaultParamNote <- function(data_frame, report_data) {
    auto_defaults <- c("drink_format","food_type","drink_type")
    if (!("default_params_used" %in% names(data_frame))) {
        data_frame[,"default_params_used"] = NA
    }
    for (i in auto_defaults) {
        print(paste("Checking", i))
        if (!(is.na(report_data[[i]]) | as.character(report_data[[i]]) == "integer(0)" | as.character(report_data[[i]]) == "NA")) {
            index_values <- report_data[[i]][[1]]
            for (j in index_values) {
                if (is.na(data_frame[j, "default_params_used"])) {
                    data_frame[j, "default_params_used"] <- list(i)
                } else {
                    data_frame[j, "default_params_used"] <- paste(
                        as.character(c(data_frame[j, "default_params_used"], i)), collapse=", "
                        )
                }
                
            }
        }

    }
    return(data_frame)
}

#' Manual parameter update function
#'
#' This function allows updating/setting of a parameter manually where one is missing or
#' incorrect. Additionally, it records which parameters have been manually added. This function
#' allows multiple rows of data to be changed at once by supplying a list of index values.
#'
#' @param data_frame a data.frame object with product data
#' @param parameter_name a chr object with name of parameter to be changed
#' @param index_list a vector object of index values of parameters to be changed
#' @param value the value to enter for the parameter
#' @return data_frame the product data with an additional column recording manual param editing
#' @seealso [AutoDefaultParamCheck()],[ReqParamCheck()]
#' @export
ManualParamUpdate <- function(data_frame, parameter_name, index_list, value) {
    if (!("manual_params_used" %in% names(data_frame))) {
        data_frame[,"manual_params_used"] = NA
    }
    for (i in index_list) {
        if (is.na(data_frame[i, "manual_params_used"])) {
                    data_frame[i, "manual_params_used"] <- list(parameter_name)
                } else {
                    data_frame[i, "manual_params_used"] <- paste(
                        as.character(c(data_frame[i, "manual_params_used"], parameter_name)), collapse=", "
                        )
        }
        data_frame[i, parameter_name] <- value
    }
    return(data_frame)
}

#' Check parameter values function
#'
#' A function that takes an input dataframe and counts unique occurrences
#' for each parameter and lists all included values. This allows you to check that no
#' values have misspelled or invalid entries.
#'
#' @param data_frame a data.frame object with product data
#' @return results a data.frame object with each named parameter and the unique occurrences of values
#' @export
CheckValues <- function(data_frame) {
    name_list <- c(names(data_frame))
    count_list <- c()
    variables_list <- c()
    for (i in names(npm_testcases)) {
        count <- length(unique(npm_testcases[[i]]))
        count_list <- c(count_list, count)
        variables <- paste(unique(npm_testcases[[i]]), collapse=", ")
        variables_list <- c(variables_list, variables)
    }
    results <- data.frame(
        "Parameter_name" = name_list,
        "Count_unique_values" = count_list,
        "Unique_values" = variables_list
    )
    return(results)
}