
name: r-check

# Only run this when the master branch changes
# this is an example of working action
# not deployed whilst repo is private

# test version
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

# This job installs dependencies and runs testthat suite
jobs:
  r-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: ['4.3.0','release' ]
    name: R ${{ matrix.R }} check
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check
    - uses: r-lib/actions/check-r-package@v2
    - name: Show testthat output
      if: always()
      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash